c:
	g++ main.cpp -O2 -std=c++17 -static -lm

r: 
	./a.out

r1:
	./a.out < in1

r2:
	./a.out < in2

r3: 
	./a.out < in3

r4:
	./a.out < in4

r5:
	./a.out < in5

ro1:
	./a.out < in1 > output1 | diff output1 out1

ro2:
	./a.out < in2 | diff in2 out2

ro3: 
	./a.out < in3 | diff in3 out3

ro4:
	./a.out < in4 | diff in4 out4

ro5:
	./a.out < in5 | diff in5 out5